### ISSUE TITLE
Add **eslint-plugin-node** plugin, and extend recommended ruleset

### ISSUE THREAD

**Issue by pdehaan** [mozilla/eslint-plugin-fxa#9]
Per the lovely conversation at https://github.com/mozilla/fxa-oauth-server/issues/527#issuecomment-372548109.

I'd probably recommend disabling/overriding the following rules from the **plugin:node/recommended** set though:

```yml
node/no-missing-require: off
node/no-unpublished-require: off
node/shebang: off
```

And for the case of [at least] **fxa-content-server**, you may want to modify the following rule since that repo uses `import`/`export` syntax and the `babel-eslint` parser:

```yml
node/no-unsupported-features: [error, {ignores: ["modules"]}]
```
